CREATE TABLE CURSOS(
IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
HORAS INT,
VALOR FLOAT(10,2),
ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS (IDCURSO);

INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BI', 30, 800.00, 1);
INSERT INTO CURSOS VALUES(NULL, 'RELATORIOS AVANÇADOS', 20, 600.00, 2);
INSERT INTO CURSOS VALUES(NULL, 'LOGICA PROGAMAÇÃO', 20, 300.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'RUBY', 30, 500.00, 4);

SELECT NOME, VALOR, HORAS, ifnull(ID_PREREQ, "SEM REQ") AS REQUISITO FROM CURSOS;

SELECT C.NOME AS CURSO, C.VALOR AS VALOR, C.HORAS AS CARGA, ifnull(P.NOME, "---") AS "PRE-REQUISITO"
FROM CURSOS C
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;