CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDOR VALUES (NULL, 'MARIA', 3245, 43256, 43215);
INSERT INTO VENDEDOR VALUES (NULL, 'JOAO', 12354, 45632, 12354);
INSERT INTO VENDEDOR VALUES (NULL, 'CLARA', 25647, 1345, 45787);
INSERT INTO VENDEDOR VALUES (NULL, 'PEDRO', 1235, 13548, 98562);
INSERT INTO VENDEDOR VALUES (NULL, 'ANTONIO', 9856, 12354, 78545);
INSERT INTO VENDEDOR VALUES (NULL, 'ANDREA', 1345, 13543, 98562);

CREATE TABLE VEND_TOTAL (
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
		DECLARE FIM INT DEFAULT 0;
		DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
		DECLARE VNOME VARCHAR(50);
		
		DECLARE REG CURSOR FOR(
			SELECT NOME, JAN, FEV, MAR FROM VENDEDOR
		);
		
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
		
		OPEN REG;
		
		REPEAT
		
			FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
			IF NOT FIM THEN
			
				SET VTOTAL = VAR1 + VAR2 + VAR3;
				SET VMEDIA = VTOTAL / 3;
				
				INSERT INTO VEND_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
				
			END IF;
			
		UNTIL FIM END REPEAT;
		
		CLOSE REG;
END
$

DELIMITER ;

CALL INSEREDADOS();

SELECT * FROM VEND_TOTAL;
