CREATE TABLE CLIENTE (
    IDCLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(70) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
    IDENDERECO INTEGER PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
    ID_CLIENTE INTEGER UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE (
    IDTELEFONE INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RESIDENCIAL', 'COMERCIAL', 'CELULAR') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INTEGER,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);




