CREATE TABLE CLIENTE (
    IDCLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(70) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
    IDENDERECO INTEGER PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
    ID_CLIENTE INTEGER UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE (
    IDTELEFONE INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RESIDENCIAL', 'COMERCIAL', 'CELULAR') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INTEGER,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE VALUES(NULL,'CELULAR','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','88687909',2);

SELECT c.nome, c.sexo, e.bairro, e.cidade, t.tipo, t.numero
FROM cliente c
	INNER JOIN
    endereco e ON c.idcliente = e.id_cliente
	INNER JOIN
    telefone t ON c.idcliente = t.id_cliente
WHERE sexo = 'f'; 

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','44522578',20);

-- Relatório geral de todos os clientes
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

-- Relatório de homens
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

-- Relatório de mulheres
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';
UPDATE CLIENTE SET SEXO = 'M' WHERE IDCLIENTE IN (15);
SELECT * FROM CLIENTE;

-- Quantidade de homens e mulheres
SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM CLIENTE 
GROUP BY SEXO;

-- IDS e email das mulheres que moram no centro do rio de janeiro e não tenham celular
SELECT C.IDCLIENTE, C.EMAIL
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO'
AND TIPO IN ('RESIDENCIAL', 'COMERCIAL');

-- RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR 
FROM CLIENTE C 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
WHERE TIPO = 'CELULAR' AND ESTADO = 'RJ';

-- RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR  DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR 
FROM CLIENTE C 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
WHERE SEXO = 'F'
AND ESTADO = 'SP';

SELECT 
    C.NOME,
    IFNULL(C.EMAIL, 'NÃO TEM E-MAIL') AS 'E-MAIL',
    E.ESTADO,
    T.NUMERO
FROM
    CLIENTE C
        INNER JOIN
    ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
        INNER JOIN
    TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE;

CREATE VIEW V_RELATORIO AS
SELECT 
    C.NOME,
    C.SEXO,
    IFNULL(C.EMAIL, 'CLIENTE SEM E-MAIL') AS 'E-MAIL',
    T.TIPO,
    T.NUMERO,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO
FROM
    CLIENTE C
        INNER JOIN
    TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
        INNER JOIN
    ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE;
    
SELECT 
    NOME, NUMERO, ESTADO
FROM
    V_RELATORIO;
    
