CREATE TABLE CLIENTE (
    IDCLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(70) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
    IDENDERECO INTEGER PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
    ID_CLIENTE INTEGER UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE (
    IDTELEFONE INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RESIDENCIAL', 'COMERCIAL', 'CELULAR') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INTEGER,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE VALUES(NULL,'CELULAR','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','88687909',2);

SELECT c.nome, c.sexo, e.bairro, e.cidade, t.tipo, t.numero
FROM cliente c
	INNER JOIN
    endereco e ON c.idcliente = e.id_cliente
	INNER JOIN
    telefone t ON c.idcliente = t.id_cliente
WHERE sexo = 'f'; 