CREATE TABLE CARRO (
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
    PLACA VARCHAR(20) NOT NULL,
    ID_MARCA INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO ENUM('M', 'F') NOT NULL,
    ID_CARRO INT UNIQUE,
    CONSTRAINT FK_CLIENTE_CARRO
    FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO)
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(20) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT NOT NULL,
    NUMERO VARCHAR(12) NOT NULL,
    TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
    ID_CLIENTE INT,
    CONSTRAINT FK_TELEFONE_CLIENTE
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO, ID_COR)
);

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);
